In [3]:
import tensorflow as tf

# each action = [0,0,0,0,0,0,1] or [0,0,0,0,0,0,-1]
# 10 actions in total
actions = tf.constant([[0,0,0,0,0,0,1], [0,0,0,0,0,0,-1], [0,0,0,0,0,0,-1]])
gripper_action = actions[:, -1]
print(gripper_action)

def invert_gripper_actions(actions: tf.Tensor) -> tf.Tensor:
    return 1 - actions

gripper_action = tf.clip_by_value(gripper_action, 0, 1)
print(gripper_action)
gripper_action = invert_gripper_actions(gripper_action)

print(gripper_action)

tf.Tensor([ 1 -1 -1], shape=(3,), dtype=int32)
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
tf.Tensor([0 1 1], shape=(3,), dtype=int32)
